/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include "ADC.h"

uint16_t Raw_val = 0;

double Sensor_val = 0.0;

int main (void) {

	int ADC_resolution  = 0;

	int ADC_bit_resolution = 8;

	double Vref = 3.00;

	 ADC1_Init();

	// ADC possible resolutions = 8-bits, 6-bits

	 ADC_resolution = ADC_resolution_calculation(ADC_bit_resolution);

    while (1) {

		Raw_val = ADC1_read();

		Sensor_val = (double)(Raw_val *Vref)/(ADC_resolution-1);

	}

	return  0;
}



